### ISSUE TITLE
Don't trust, make sure!

### ISSUE THREAD

**Issue by jerguslejko** [matuskropuch/beauty-and-simplicity#2]
When calling `$filesystem->makeFile('./test.txt');` I have *no way* of knowing whether the file was created or not.

Although underlying logic that you use provides that information. When calling `touch('./test.txt');`, the return value is either `true` or `false` depending on whether the file was created.

💻 🌵 🍰

**Comment by matuskropuch** [comment]
resolved in 295d0539f717db1c7ae8aeb640e7b22aa3a8e095 :poultry_leg:
