### ISSUE TITLE
Not even cool

### ISSUE THREAD

**Issue by jerguslejko** [matuskropuch/beauty-and-simplicity#3]
Bro, i mean....

where the *f*u*c*k* is readme? that's the place for all those cool emojis!!!

🌵 🍰 🐟 🔫 :fu: 

and, yeah, we write `README.md` in markdown, #bjač

**Comment by matuskropuch** [comment]
resolved in 96e4428efac828f9a82a93ab7579e27f20374462 :cake: :cake: :cake:
